- .github/workflows/empty-test.yml
Mostly this PR is a test to verify that I can set up github workflows, which will helpful later on when we have some unit tests. For now, this will prevent us from merging empty PRs, which is more of a redundant check, useful for large projects with many people, but neutral in helpfulness for tune tracer.
Verified that this PR passed the yaml test. Once this merges, I'll verify that it fails empty PRs.
-----
> add github workflow to detect empty PRs

- backend/package.json
- frontend/package.json
- package.json
Added `pnpm debug`, which will allow devs to attach a debugger to a service. I also added some dev dependencies in preparation for an eventual debug & run button.
Used `pnpm debug` in backend service folder and successfully attached a debugger.
-----
> update package.json files for debugging

- backend/package.json
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/firebaseSecrets.ts
- backend/src/main.ts
- backend/src/testController.ts
Added a function for users to sign up.
Currently, `FirebaseWrapper` is acting as a wrapper function to handle all firebase calls. I will probably have to refactor it at some point when I figure out a better design pattern, but for now, it will act as an abstraction layer between firebase and our code.
The function `signUpNewUser` takes an email, password, and displayName and returns a boolean promise of whether or not the user creation was successful.
Further features could be added to this function.  Let me know if I should prioritize any, including:
* making display names optional
* adding some encryption or security component to handling passwords
* returning the actual error if the user creation was unsuccessful
* performing a retry of user creation if it unsuccessful (only for some …
> add user sign up to backend

- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/testController.ts
Added sign in function to firebase wrapper.
In the future, I will need to add a way for devs to access the user credentials that are returned, either by returning the credentials or storing them in the wrapper, depending on what is necessary.
Uncommented the `runTest()` call in the main file.  This called the sign in function, and I verified that the success print statement was called.
-----
> add log in function to firebase wrapper in backend

- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/firebaseSecrets.ts
- backend/src/testController.ts
Added support for simple CRUD operations for music documents.
Each document has a string id that is generated upon the first creation of the document. Any future reads, deletions, and updates require this id to occur.
***NOTE***: This support is meant for the backend only. I will add an additional layer of functions to actually be called by the APIs.
Used the functions in the `testController` file to test the CRUD functions. I have not yet tested what happens on a failure.
-----
> add CRUD operations for composition documents

- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/documentTypes.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/firebase-utils/documentConversionUtils.ts
- backend/src/security-utils/permissionVerification.ts
- backend/src/testController.ts
Added a file `documentOperations.ts` for the frontend/APIs to access and use. This file will do all the firebase interactions for the developer, so you don't have to interact directly with firebase at all.
Additionally, developers will want to use the `Document` schema (type) defined in the `documentTypes.ts` file, which is how the document data will be passed around.
> add abstraction layer to document CRUD operations for api endpoints/frontend

- lib/documentTypes.ts
I added metadata for an emoji and color for the document preview on the storage page. They are currently set as optional parameters, so devs should make sure to check if they are `undefined` when using them.
Edits to these variables is currently not supported (metadata updates coming soon), but they can be accessed along with the rest of the document metadata.
No test. Compiler should catch errors.
-----
> add optional preview customizations in document type defintion

- backend/package.json
- backend/tsconfig.json
After deleting my local node_modules folder, the compiler was complaining that it could not recognize the `process.exit(0)` command in the `testController.ts` file, so I installed nodes/types as a dev dependency. This may need to be converted to a prod dependency in the future.
Used `pnpm install` and `pnpm build`.
-----
> fix pnpm install issue (add node types to dev dependencies)

- backend/package.json
- backend/src/main.ts
- backend/tsconfig.json
pnpm scripts were not working properly after the previous tsconfig edits. I had to add aliases and fix the rootDir & baseDir in the tsconfig file.
Deleted all `dist` and `node_modules` folders and then ran the following commands while in the backend directory:
1. `pnpm install`
2. `pnpm build`
3. `pnpm dev`
4. `pnpm debug`
Got no errors for all commands
-----
> fix pnpm scripts for backend

- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/testController.ts
Added functions that allow updates to a document's metadata. Specifically, updates to the:
* preview emoji
* preview color
* share style
* share user list
Ran the `testDocumentMetadataUpdate` function in the `testController.ts` file, which called all the new update functions. I then verified that the changes were reflected in Firestore.
-----
> add functions for updating document metadata (backend)

- backend/src/firebase-utils/FirebaseWrapper.ts
- lib/UserEntity.ts
I added a type definition for a user entity, which is how user account information (other than passwords and emails) will now be stored. This will make updating the user account information (like the shared and owned documents) easier.
Ran the `testSignUp` function in the `testController.ts` file.
-----
> formally define user entities in firestore

- backend/package.json
- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/main.ts
- backend/src/tests/testController.ts
Bug fix: the metadata updates to the share list weren't being reflected in the shared user lists in Firestore. I fixed this by adding the appropriate calls to the two metadata update share functions.
Wrote a more unit test-like function for checking that the metadata update functions correctly impact the database.  Eventually, I want this test to be called automatically before every merge into main.
-----
> [Bug Fix] update the user lists when updating the document sharing metadata

- backend/package.json
- backend/src/document-utils/realtimeDocumentUpdates.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/tests/testController.ts
Add a `subscribeToDocumentUpdates`, which takes in the document id of a single document to watch. Every time the document changes (this also includes the first call to the function, since before then the document is considered undefined), an update function is called. This update function is passed in as a parameter to the subscription and takes in a Document. The update function will be called on the newest document in Firebase, whenever there is one, until the process is exited.
Ran the `testDocumentChanges` function in the `testController.ts` file. This function calls the subscription function. I verified that a change in Firestore was reflected in a console.log statement after running the test function.
-----
> add function to monitor realtime updates for single documents

- backend/src/document-utils/documentBatchRead.ts
- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/security-utils/permissionVerification.ts
- backend/src/tests/testController.ts
This PR adds permission checks before a user can read or write to a document.  Before a user can read or write to a document, their email will be checked against the set permissions of the document.
In most cases, a `writerEmail` or `readerEmail` is now a required parameter in the document CRUD operation functions. These variables are for the user that is attempting to perform the read/write.
Overhauled the `testController.ts` file to work with the updated CRUD functions. I got the `testDocumentMetadataUpdates` working, which tests creations, reads, and updates for documents.
Ran `pnpm install`, `pnpm build`, `pnpm dev`, and `pnpm debug` in the backend folder.
-----
> auth users before reads and writes

- backend/src/document-utils/documentBatchRead.ts
- backend/src/document-utils/documentOperations.ts
- backend/src/tests/testController.ts
- lib/documentTypes.ts
Instead of giving the storage page (name TBD) a list of documents, this PR instead updates the functions to now return a list of DocumentPreviews (definition in the `documentTypes.ts` file).  The DocumentPreview type contains all metadata fields plus the document_title field.
Updated and ran the `testDocumentMetadataUpdates` function in the `testController.ts` file, and verified that the list of shared documents with the secondary and tertiary user emails were formatted correctly.
-----
> extract document previews instead of documents for the user access lists

- backend/src/scripts/refreshFirestoreUserAccessLists.ts
- backend/src/tests/testController.ts
Added a tooling script that will let us devs force refresh the firestore database. Specifically, this script will refresh all user lists of owned and shared documents.  This is specifically useful for automated document deletions and dev testing/setup.
Ran the new script and the `testDocumentMetadataUpdates` function in the `testController` file.
-----
> added a force refresh script for the shared and owned lists of documents in firestore

- backend/src/document-utils/realtimeDocumentUpdates.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/firebaseSecrets.ts
- backend/src/tests/testController.ts
- lib/UserEntity.ts
Using the Realtime Database (as opposed to Firestore), you can now register a user to a document. This will allow other users to "see" who's online.  Right now, you can only add an entry of a user to a subscribed document, and the entry deletes itself when the user disconnects from Firebase.  Later, I will tie this more closely to document subscriptions, so that these entries can be updated and trigger local changes.
Ran the new function and checked that the Realtime Database added and then deleted the user entry.
-----
> register users as "on" documents

- backend/src/document-utils/realtimeOnlineUsers.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/tests/testController.ts
- lib/userTypes.ts
Add the subscribe to user pool function, so that the frontend can update the existing OnlineEntity objects for a document.
Ran the `testUserRegistrationToDocument` in the `testController.ts` file. 
-----
> subscribe to user pool (online users) updates

- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/realtimeDocumentUpdates.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/tests/testController.ts
- backend/src/user-utils/getUserData.ts
This PR binds the subscribe to document changes with the subscribe to user pool changes functions. Essentially, only 1 API will need to be created to subscribe to a document, instead of two.
Ran the `testDocumentChanges` function in the `testController` file.  It calls the subscribe to document function and then triggers a couple of changes. I monitored the console to verify that the output was expected.
-----
> tie document subscription with user pool subscription together

- backend/src/document-utils/documentBatchRead.ts
- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/realtimeOnlineUsers.ts
- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/scripts/refreshFirestoreUserAccessLists.ts
- backend/src/security-utils/permissionVerification.ts
- backend/src/tests/testController.ts
- lib/documentTypes.ts
After running into another issue with using user emails as ids in the database, I decided it was time to convert everything to use user ids as the main ids. It was a pain, but I it'll hopefully end the issues I encountered in the database.
I tested a couple of functions in the test file. I know I should test more comprehensively, but I don't feel like it right now. I will do a full check when I write unit tests for the backend.
-----
> use user ids for everything instead of user emails

- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/scripts/refreshFirestoreUserAccessLists.ts
- backend/src/security-utils/permissionVerification.ts
- backend/src/tests/testController.ts
- lib/documentTypes.ts
Separated the logic for share links/codes and sharing with single users.  
Note: the share style with the user takes priority over the share link, even if the share link gives a higher priority. If we have anonymous users, this can be used to bypass the user allotted permissions, if applicable.
Ran and fixed the single unit test in the test controller file.
-----
> separate sharing by user from sharing by link or code

- backend/src/document-utils/documentBatchRead.ts
- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/realtimeDocumentUpdates.ts
- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/scripts/refreshFirestoreUserAccessLists.ts
- backend/src/tests/testController.ts
- lib/userTypes.ts
Added a list in the UserEntity type specifically for holding document ids of documents accessed through links or codes instead of by being shared directly.  This list is updated whenever a user "gets" a document that has a non-private share style and that user is not the owner or on the share list.
Unit test. I also added a part of the unit test that specifically checks for adding/removing access list documents.
-----
> add access list for documents accessed through a code or link

- backend/src/document-utils/documentBatchRead.ts
- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/document-utils/updateUserLevelDocumentProperties.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/tests/testController.ts
- lib/src/UserEntity.ts
- lib/src/documentProperties.ts
Made `is_favorited`, `preview_emoji`, and `preview_color` into user-level properties, such that they are localized to just a single user. This way, a user editing their preview, does not impact another user's preview.
Added a unit test and updated previous unit tests. Ran them, fixed bugs, and ensured no errors thrown.
-----
> user level document properties

- backend/src/comment-utils/commentOperations.ts
- backend/src/document-utils/realtimeDocumentUpdates.ts
- backend/src/document-utils/realtimeOnlineUsers.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/security-utils/permissionVerification.ts
- backend/src/tests/testController.ts
- lib/src/Comment.ts
- lib/src/documentProperties.ts
CRUD operations for comments.  Currently, you can only "get" a comment, if you subscribe to a document's pool of comments.
Created a unit test, ran, debugged...
-----
> add CRUD operations and subscription for comments
