- README.md
- backend/README.md
Updated the README text for the whole project and in the backend in order to better reflect the purpose and tools of the sections of the project after the frontend was populated with its initial skeleton.
None needed
-----
> update READMEs to reflect frontend construction

- backend/src/document-utils/documentBatchRead.ts
- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/documentTypes.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/firebaseSecrets.ts
- backend/src/testController.ts
This PR adds the functionality to get and update the list of user owned documents and the documents shared with a particular user. 
Using the testController.ts file:
* Test the document creation function to verify the user owned list gets updated
* delete the document to verify the user owned list is updated
* call the `getDocumentsOwnedByUser` on an established user and an absent one
* call the `getDocumentsSharedWithUser` function for an existing and absent user
Note, updating sharing details for a document is not yet implemented, so it is untested for now.
Another Note: a non-existing user generates errors in most of this code
-----
> document batch operations

- backend/src/document-utils/documentBatchRead.ts
- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/realtimeDocumentUpdates.ts
- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/scripts/refreshFirestoreUserAccessLists.ts
- backend/src/security-utils/permissionVerification.ts
- lib/UserEntity.ts
Strictly formatting changes (zero behavioral changes). Mostly this PR contains updates for the comments in the various backend files, but I used this PR as an excuse to also run a linter on some of the files.
None
-----
> updating formatting and comments in backend .ts files

- backend/src/document-utils/realtimeDocumentUpdates.ts
- backend/src/document-utils/realtimeOnlineUsers.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/tests/testController.ts
- lib/UserEntity.ts
For a user registered to a document, this PR allows those users to update their last active time and cursors.
Ran the `testUserRegistrationToDocument` in the `testController.ts` file, which tests the three online user functions in the `realtimeOnlineUsers` file
-----
> allow users to update their cursors and last active time for online tracking

- backend/src/firebase-utils/FirebaseWrapper.ts
Made generic versions of the read, update, and delete functions that interact with Firestore. This will make it less tedious to add more collections in Firestore and their CRUD variations to the wrapper.
Ran unit test of test controller file and verified no thrown errors.
-----
> add generic firestore CRUD functions to FirebaseWrapper

- backend/src/document-utils/sharing/ShareCodeEntity.ts
- backend/src/document-utils/sharing/sharingUtils.ts
- backend/src/firebase-utils/FirebaseWrapper.ts
- backend/src/firebaseSecrets.ts
- backend/src/tests/testController.ts
Added functions for sharing code creation, deletion, and reading (get the document id associated with a share code).
Added a unit test for sharing codes that tests the creation, deletion, and reading functions.
-----
> add sharing codes functionality

- frontend/src/app/landingpage.tsx
- frontend/src/app/login/page.tsx
- frontend/src/app/storage/FiltersNavbar.tsx
- frontend/src/app/storage/SearchBar.tsx
- frontend/src/app/storage/page.tsx
Storage page styling and concepts. There is no data actually being read or taken in this version.
Nothing really to test at the moment, no endpoints are active.
-----
> Storage page creation

- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/updateDocumentMetadata.ts
- backend/src/tests/testController.ts
- lib/documentTypes.ts
Add favoriting for the authors. Authors can now "star" their favorite documents so that they can filter by favorites in their owned documents tab.
Added the new metadata update function to the manual unit tests.
-----
> initial commit

- lib/package.json
- lib/src/CompToolData.ts
- lib/src/Measure.ts
- lib/tsconfig.json
I added package.json and tsconfig.json files to lib, so that I could import libraries like vexflow into the project.
I also copied over the Measure definition to lib, so that CompToolData.ts can properly import it.  Note that I copied the file without deleting the original.
Reran backend unit tests.
-----
> add project files to lib and move composition data files to lib

- backend/src/document-utils/realtimeDocumentUpdates.ts
Move permissions check from only occurring during the first access to every read access.
Hope
-----
> verify permission to read for every change (backend)

- backend/src/document-utils/documentOperations.ts
- backend/src/document-utils/updateDocumentMetadata.ts
Only the author should be able to update metadata (share style and shared users), so I added a check for this.
Ran unit tests.
-----
> require author status for metadata updates

- backend/src/document-utils/documentOperations.ts
- backend/src/tests/testController.ts
Converted the updateDocument function to updatePartialDocument. The new function can manage both partial and full updates for the document content.
Security note: this function will allow any kinds of updates to pass. Please don't be mean and pass unintended updates through it 🥺 
Ran backend unit tests
-----
> add partial document content updates function

- frontend/src/app/composition_tool/page.tsx
Playback, add comment, and toolbar tab UI elements.
n/a
-----
> More Composition Tool UI elements (Playback and Add comment)

- frontend/src/app/storage/page.tsx
All styling for document cards is finished, all that needs to be done is grab data from APIs and display them in the correct spots that are marked. The profile button at the top right now is meant to show the user's registered name and on click shows their registered email AND a logout button.
n/a
-----
> Profile, Delete, Favorite, Title Overflow + Navigation styling

- functions/src/backend/src/firebase-utils/FirebaseWrapper.ts
- functions/src/backend/src/tests/testController.ts
- functions/src/backend/src/user-utils/getUserData.ts
`getUserIdFromEmail(userEmail: string)` returns the id or throws an error
added to unit tests
-----
> get user id from user email

- frontend/src/app/composition_tool/page.tsx
- functions/src/index.ts
> changes for cursor support

- frontend/src/app/composition_tool/page.tsx
- frontend/src/app/signup/page.tsx
- functions/src/lib/src/Document.ts
> fixed signUp page and included errors

- frontend/src/app/composition_tool/page.tsx
- frontend/src/app/signup/page.tsx
- functions/src/lib/src/Document.ts
> Fixed signup

- frontend/package.json
- frontend/src/app/composition_tool/page.tsx
- frontend/src/app/notFoundPage.tsx
added 404 page and get edit access
:(
-----
> Permissions routing

- frontend/package.json
- frontend/src/app/global.css
- frontend/src/app/login/page.tsx
- frontend/src/app/signup/page.tsx
- frontend/src/components/AuthInput.tsx
- frontend/src/styles/auth-styles.ts
- frontend/src/utils/callAPI.ts
- functions/src/backend/src/tests/testController.ts
- functions/src/index.ts
Sign up page prettifying
`npm run dev`
-----
> 10-29 signup page

- frontend/src/app/composition_tool/ToolbarHeader.tsx
- frontend/src/app/composition_tool/page.tsx
Button icons and functionalities. Key Signatures WIP.
-----
> Button functionalities

- frontend/src/app/global.css
- frontend/src/app/landingpage.tsx
- frontend/src/components/LandingPageContent.tsx
Created a basic landing page. 
It still needs images and the header should be abstracted and reused in the signup and login pages.
`npm run dev`
-----
> 10-29 landing page

- frontend/src/app/storage/DocCard.tsx
- functions/src/lib/src/MeasureData.ts
- functions/src/lib/src/ScoreData.ts
- lib/src/Document.ts
what the title says
none :/
-----
> reupdate lib in functions and redeploy apis

- frontend/src/app/composition_tool/page.tsx
- functions/package.json
- functions/src/backend/src/comment-utils/commentOperations.ts
- functions/src/backend/src/document-utils/documentBatchRead.ts
- functions/src/backend/src/document-utils/documentOperations.ts
- functions/src/backend/src/document-utils/realtimeDocumentUpdates.ts
- functions/src/backend/src/document-utils/realtimeOnlineUsers.ts
- functions/src/backend/src/document-utils/updateDocumentMetadata.ts
- functions/src/backend/src/document-utils/updateUserLevelDocumentProperties.ts
- functions/src/backend/src/endpoints/readEndpoints.ts
- functions/src/backend/src/firebase-utils/FirebaseWrapper.ts
- functions/src/backend/src/lib/package.json
- functions/src/backend/src/lib/src/Comment.ts
- functions/src/backend/src/lib/src/Document.ts
- functions/src/backend/src/lib/src/MeasureData.ts
- functions/src/backend/src/lib/src/ScoreData.ts
- functions/src/backend/src/lib/src/SelectedNote.ts
- functions/src/backend/src/lib/src/StatusCode.ts
- functions/src/backend/src/lib/src/StaveNoteData.ts
- functions/src/backend/src/lib/src/UpdateType.ts
- functions/src/backend/src/lib/src/UserEntity.ts
- functions/src/backend/src/lib/src/documentProperties.ts
- functions/src/backend/src/lib/src/realtimeUserTypes.ts
- functions/src/backend/src/lib/tsconfig.json
- functions/src/backend/src/scripts/refreshFirestoreUserAccessLists.ts
- functions/src/backend/src/security-utils/getUserAccessLevel.ts
- functions/src/backend/src/security-utils/permissionVerification.ts
- functions/src/backend/src/tests/testController.ts
- functions/src/index.ts
- functions/tsconfig.json
Reverted lib folder deletion/syncing
Actually used the test feature in Google Cloud
-----
> 10-30 even more bug fixes

- frontend/src/app/composition_tool/ToolbarHeader.tsx
- frontend/src/app/composition_tool/page.tsx
Dots and Key Signatures are up and functional! UI might change in future versions
-----
> Dots and Key signature functionality

- frontend/src/app/storage/page.tsx
- frontend/src/app/storage/storage-tutorial.tsx
Reversion of storage tutorial as it resulted in a runtime error. Keeps UI/UX fixes.
-----
> SAFE STATE Storage tutorial REVERSION

- frontend/src/app/composition_tool/ToolbarHeader.tsx
- frontend/src/app/storage/page.tsx
As seen in title. Viewers are now unable to open share modal and help button
-----
> Pause, favorites removed. More viewer access restrictions.

- frontend/src/app/composition_tool/KeybindModal.tsx
- frontend/src/app/composition_tool/ToolbarHeader.tsx
- frontend/src/app/landingpage.tsx
Keyboard shortcut modal is now live! Removed security tab on frontpage.
-----
> Keyboard Shortcut Modal

- frontend/src/app/composition_tool/sharing/CollaboratorCard.tsx
- frontend/src/app/composition_tool/sharing/SharingModal.tsx
- frontend/src/app/composition_tool/sharing/sharing_types.ts
- functions/src/backend/src/document-utils/documentBatchRead.ts
- functions/src/backend/src/firebase-utils/FirebaseWrapper.ts
- functions/src/backend/src/user-utils/updateUser.ts
- functions/src/index.ts
> Polishing week 1 - batch commits

- frontend/src/app/composition_tool/ToolbarHeader.tsx
- frontend/src/app/storage/page.tsx
Fixed bug with the profile menu being jittery with longer emails. The profile button is also now accessible on the editor page.
-----
> Profile button on editor page

- frontend/src/app/composition_tool/KeybindModal.tsx
- frontend/src/app/composition_tool/ToolbarHeader.tsx
- frontend/src/app/composition_tool/sharing/SharingModal.tsx
- frontend/src/app/global.css
- frontend/src/app/profile/page.tsx
- frontend/src/app/storage/DocCard.tsx
- frontend/src/app/storage/page.tsx
Icons added to a lot of buttons. 
Headers are now more consistent between pages. 
Color Swatch is now less awkward (a grid that actually is filled out correctly)
-----
> More UI tweaks

- frontend/src/app/storage/DocCard.tsx
- frontend/src/app/storage/page.tsx
DocCards cascading issue please go away...
DocCards are now more uniform with their labeling, no more offcenter weirdness if names are different lengths
Sorting by recent has the icon make sense now, AND IS DEFAULTED!!!
-----
> OK DOCCARDS SHOULD FINALLY BE OK

- frontend/src/app/composition_tool/onlineUsers/OnlineUserIcon.tsx
- frontend/src/app/composition_tool/onlineUsers/OnlineUsersToolbarContainer.tsx
- frontend/src/app/landingpage.tsx
- frontend/src/app/storage/DocCard.tsx
- frontend/src/app/storage/page.tsx
various small polishes
`npm run dev`
-----
> Thur Morning Batch Polishes
